spring:
  datasource:
    url: jdbc:h2:mem:course
    username: hb
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
git:
  api:
    user: https://api.github.com/users/{login}